# Site
name: "Teamclipper"
title: "Teamclipper"
description: "Teamclipper: Private and collborative bookmarking for your company."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'G-1CL4KPDH3J'
disqus: 'www-teamclipper-com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vishwesh:
    name: Vishwesh
    display_name: Vishwesh
    gravatar: cdd833fd7ce305642140987622646aba
    email: vishwesh@teamclipper.com
    web: https://www.teamclipper.com
    twitter: https://twitter.com/vishweshji
  akshay:
    name: Akshay
    display_name: Akshay
    gravatar: b4bb0d20bf3d384617e93eeec7c83cfb
    email: akshay@teamclipper.com
    web: https://www.teamclipper.com
    twitter: https://twitter.com/akshay_deo
  harshad:
    name: Harshad
    display_name: Harshad
    gravatar: fea8da0d503a35dbfb2a6dcb587b9409
    email: harshad@teamclipper.com
    web: https://www.teamclipper.com
    twitter: https://twitter.com/harshad_geek

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
